### PR TITLE
Convert .py indentation from tabs to spaces and remove trailing spaces

### PR DESCRIPTION
**Pull request by Strilanc**
To produce the changes in this PR I ran exactly these three bash commands:

    files=$(find | grep \.py$)

    for file in $files; do sed -i 's/\t/    /g' ${file}; done

    for file in $files; do sed -i 's/ *$//g' ${file}; done

### CODE REVIEW

**Comment by Strilanc** [comment]
For https://github.com/ProjectQ-Framework/ProjectQ/issues/12

**Comment by damiansteiger** [comment]
Thanks a lot. We have not decided about spaces vs tabs yet. Anyway we will change it once we integrate FermiLib into ProjectQ.

**Comment by Strilanc** [comment]
@damiansteiger Integrating FermiLib is going to take months. There's no reason to block a tiny change like this on a large library like that.

The tab and space mixing causes me minor problems every time I touch the code. Pycharm can't figure out if I want lines indented with tabs or spaces, so it just kinda chooses arbitrarily. Differing tab widths mean existing code doesn't line up argument-by-argument like it was intended to. I can never tell if something will line up on github or not before actually doing a push.

Just make a decision about whether to do the spaces conversion or not. I'm in favor of spaces for the same reasons outlined in PEP8. But mostly I'm in favor of not unnecessarily pushing off the decision.

**Comment by Strilanc** [comment]
Note that by "in favor" of spaces I mean *strongly* in favor. PEP8 should win unless there's a good reason not to use it.

And if we're using tabs, we need to actually ban fine alignments and set up automatic lint checks to catch spaces sneaking in. A lot of tools insert spaces when you split code between lines.

**Comment by damiansteiger** [comment]
Fair enough, we increased priority of this issue and will decide and fix it in the next days.

By the way: Integrating FermiLib will not take months ;)

**Comment by damiansteiger** [comment]
Thanks for your suggestion to move to spaces instead of tabs. We have decided to change indentation to 4 spaces as suggested and hope that it will make it easier for developers to contribute. While our previous indentation (tabs for semantic indentation and spaces for the rest) worked well, it did create more confusion than necessary, see e.g. #12.

@thomashaener took time to not just change the indentation but at the same time also enforce a the line width to 79 character in order to be fully PEP8 compatible, see pull request #29. Therefore, I am closing this pull request.

**Pull request closed without merging**
