### PR TITLE
Break cyclic dependency on DirtyQubitTag by moving it to projectq.tags

### PR DESCRIPTION
**Pull request by Strilanc**
Part of fixing issue https://github.com/ProjectQ-Framework/ProjectQ/issues/93

### CODE REVIEW

**Comment by thomashaener** [comment]
To me, DirtyQubitTag would make sense in either meta or types. I don't think having it in cengines makes sense...

**Comment by Strilanc** [comment]
`DirtyQubitTag` is implicitly part of the definition `BasicEngine`'s `allocate_qubit` method. So `DirtyQubitTag` is forced to be a dependency of `cengines`. Since `cengines` is a dependency of `meta`, `DirtyQubitTag` can't go in `meta` without creating a cycle.

One alternative would be to split `meta` into two parts, one below `cengines` and one above.

**Comment by thomashaener** [comment]
I realize that this introduces a cycle, but it's a meta tag and as such it belongs into meta. If I were looking for this file, `cengines` would be the last place I'd expect it to be.

**Comment by Strilanc** [comment]
How about a separate directory for tags called `tags`? That would separate the no-dependency tag classes from the many-dependency command modifier classes.

**Comment by thomashaener** [comment]
Is the cyclic dependency creating issues? Adding a separate directory just for tags seems a bit extreme.

**Comment by Strilanc** [comment]
In general, cyclic dependencies between modules are bad. This particular cyclic dependency is bad because it forces an import inside a method that can run during shutdown. It triggers additional errors.

**Comment by Strilanc** [comment]
Is there anything holding this up?

**Pull request closed without merging**
