### PR TITLE
Bernstein-Vazirani tutorial for ProjectQ v0.4.2

### PR DESCRIPTION
**Pull request by cmleecm**
I have created a Bernstein-Vazirani tutorial jupyter notebook and would like to contribute to the examples.

### CODE REVIEW

**Comment by Takishima** [comment]
Feel free to do so by either pushing it to your master branch (in which case the changes will appear in this PR) or push those changes into a new branch and open a new PR.

**Comment by cmleecm** [comment]
> Feel free to do so by either pushing it to your master branch (in which case the changes will appear in this PR) or push those changes into a new branch and open a new PR.

It seems I have already push it to my master branch. Is there anything else I need to do?

**Comment by cmleecm** [comment]
Help needed here. I have changed the base branch to the master branch. Is this pushing to the master branch?

**Comment by Takishima** [comment]
You are now indeed pushing to the master branch, but because you were probably working off of the develop branch previously, a bunch of unwanted commits have made their way into this PR.

Could you please apply your changes from your `develop` branch and then do a new PR between the current `develop` and your fork?

**Comment by cmleecm** [comment]
Got it. I have created a new pull request #341 to merge the newly added berstein-vazirani_tutorial.ipynb from cmleecm:develop to ProjectQ-Framework:develop

**Pull request closed without merging**
