### PR TITLE
Extract _uncompute_assuming_no_deallocs from ComputeEngine.run_uncompute

### PR DESCRIPTION
**Pull request by Strilanc**
Follow-up to https://github.com/ProjectQ-Framework/ProjectQ/pull/96.

~~Comes after (includes) https://github.com/ProjectQ-Framework/ProjectQ/pull/108.~~

### CODE REVIEW

**Comment by Strilanc** [comment]
Good to go.

**Comment by Strilanc** [comment]
Is there anything holding this up?

**Comment by damiansteiger** [comment]
Sorry for the delay but I had to prioritize. There are some new features and improvements in the installation process which I want to take care first.

I will have time to work through all open pull request latest early next week.

**Comment by damiansteiger** [comment]
Thanks for the suggested change. I consider the original code comments more understandable and it is also faster as it does not require additional function calls, therefore I close this issue until there is a good reason to refactor this code.

**Pull request closed without merging**
