### PR TITLE
Fix ControlledGate failing when a register is empty

### PR DESCRIPTION
**Pull request by Strilanc**
- Fixed make_tuple_of_qureg assuming first register will contain items
- Fixed ControlledGate overriding __or__ instead of generate_command
- Added test of n=0 case

### CODE REVIEW

**Comment by Strilanc** [comment]
This is ready for review. @damiansteiger

**Comment by Strilanc** [comment]
Now blocked by issue https://github.com/ProjectQ-Framework/ProjectQ/issues/56

**Comment by Strilanc** [comment]
Ready for review.

**Comment by thomashaener** [comment]
Thanks! Now n=0 fails if there is no control register, but I think this should be fine since there's a nice exception explaining what went wrong... or do we want to support both cases?

**Comment by Strilanc** [comment]
I think the correct behavior, when all registers are empty, is usually to do nothing. But that is more likely to have some exception I haven't thought of, and can be done in a separate PR.

**Pull request merged**
