### PR TITLE
Define hash for Gates, use Gate objects as keys in ResourceCounter

### PR DESCRIPTION
**Pull request by kevinsung**
Addresses #189 .

I defined the hash of a gate as the hash of its string representation. Note that if a subclass of `BasicGate` (or any class) defines its own `__eq__`, then Python 3 automatically sets its `__hash__` method to `None`, so you need to redefine its `__hash__` method.

### CODE REVIEW

**Comment by thomashaener** [comment]
Thanks a lot! Could you also quickly add two small tests for the BasicPhase/RotationGate hash functions?

**Comment by kevinsung** [comment]
Ok I did it. For some reason I can't get pytest working with this project; I keep getting the error
```
ImportError: cannot import name 'MappingProxyType'
```
I think the tests will pass though.

**Comment by kevinsung** [comment]
Nevermind, I got pytest working. Now I'm just fixing the tests.

**Comment by kevinsung** [comment]
Ok, I have discovered a potential problem with my scheme. It assumes that if `G1 == G2` evaluates to true, then `str(G1) == str(G2)` also evaluates to true, for any BasicGates `G1` and `G2`. This is not true for BasicRotation/PhaseGates, for instance, if they have angles that differ by a nonzero amount less than `EQ_TOLERANCE`. This can be fixed by redefining the `__str__` function to round the angles first, but in general we would need to enforce that `G1 == G2` imples `str(G1) == str(G2)`. Are you okay with having this be a restriction throughout ProjectQ? I think it is a sensible one.

**Comment by thomashaener** [comment]
pytest: Great, I'm glad it's working now.
str & equality: Yes, I agree that enforcing this is reasonable.

Thanks!

**Comment by kevinsung** [comment]
Ok, I wrote the tests, but making them pass is actually way more annoying than I expected due to the subtleties of floating point arithmetic. I'll have to think about it more later.

**Comment by kevinsung** [comment]
To make things work out, I made the string representation have one less significant digit than the precision specified by `EQ_TOLERANCE`. I hope that's okay.

**Comment by kevinsung** [comment]
This makes the tests pass, but on further thought this still doesn't work in complete generality... perhaps we need to ditch this idea entirely. The problem is that you can always have two values that are very close, but one gets rounded up and the other gets rounded down. I haven't yet thought of a good way to get around this.

**Comment by kevinsung** [comment]
One possible solution is to always round the angle before storing it; that would remove the need for a custom `__eq__` function. Not sure if this is desirable.

**Comment by kevinsung** [comment]
I made things work by modifying both `__str__` and `__eq__`. Let me know if you find these changes unacceptable.

**Comment by thomashaener** [comment]
I think this is a good way of doing it, thanks a lot!

Coveralls reports that there are still 3 lines which never get called by the tests (the lines which set the angle to zero if it was close to 2pi or 4pi for the two `tex_str` methods and for `BasicPhaseGate.__eq__`). Could you add such angles to the tests as well? That would be great.

**Comment by kevinsung** [comment]
A variable called `EQ_TOLERANCE` is also defined and used elsewhere (namely, ops/_qubit_operator.py). It's possible that the same concept will be used elsewhere in the future. What do you think of making it (perhaps EQ_PRECISION too) a global variable defined somewhere high up (maybe a file like `projectq/config.py`)?

**Comment by thomashaener** [comment]
Yes, we might also want to do something like that at some point. But defining a tolerance specific to angles would facilitate the implementation of str, eq, ... since we could just round upon initialization and then also carry out single-qubit rotation synthesis using the same tolerance (once this is implemented).

Having one global tolerance may also not be enough, so we might even want to be able to specify the tolerance for every rotation gate instance... but we can also address this later.

**Comment by kevinsung** [comment]
If we round the angle upon initialization, that would remove the need for an `__eq__` method altogether. I actually thought of that but wasn't sure if it was desirable to always store only the rounded angle. I think this is a good way too though; would you like me to implement it?

**Comment by kevinsung** [comment]
I like the idea to round the angles upon initialization. I'll go ahead and implement it later today.

**Comment by kevinsung** [comment]
Ok, I've done it. Let me know if there's anything else.

**Pull request merged**
