### PR TITLE
Rename Command.all_qubits -> all_quregs

### PR DESCRIPTION
**Pull request by Strilanc**
There are many other cases where qubit should be qureg, but this one was easily fixed by search-and-replace.

Note that this will merge-conflict with other pending PRs.

### CODE REVIEW

**Comment by Strilanc** [comment]
Is there anything holding this up?

**Comment by damiansteiger** [comment]
I don't see any difference in `all_qubits` vs `all_quregs` hence I would stay with the old one for consistency.

We have `eng.allocate_qubit()` hence we use the term "qubit" and therefore I'd say `all_qubits` is appropriate.

**Comment by Strilanc** [comment]
If a method returns a Qureg, it should not have "qubits" in the name instead of "qureg". This is especially bad in a dynamic language like python! Names are very important!

The other methods aren't examples of good naming, they are other examples of things that need to be renamed. This PR is just the first one that I renamed.

**Comment by damiansteiger** [comment]
I don't think the name suggests a specific return format of `all_qubits`. Hence, looking up the docs is anyway required.

Btw, it does not return a Qureg either but rather a tuple of quregs as described in the docs.

**Comment by Strilanc** [comment]
@damiansteiger I edited my comment to say "list of quregs" instead of "qureg" (probably while you were reading it; sorry).

I strongly disagree about the name suggesting a specific return type. It says "qubits", so I expect back a flat collection of qubits. And even if it didn't imply that, telling me nothing instead of the actual structure is a serious naming faux-pas. The name is the most important piece of documentation about a method that there is; we shouldn't be wasting it on words that convey no information or misleading information.

**Comment by maffoo** [comment]
I agree with @Strilanc that it can be confusing to use `qubit` in the name of methods and properties that in fact return `Qureg` objects. This tripped me up in the past when using `allocate_qubit` which returns a qureg, not a qubit (there's also an unfortunate asymmetry with `deallocate_qubit` which takes a qubit as the name indicates, not a qureg). I do think there's room to clean this up and make the names more consistent.

It might also help to modify the code so that the distinction between a qubit object and a qureg of length 1 is less pronounced, but one would have to think through the consequences of that very carefully, especially given python's dynamic character.

**Comment by damiansteiger** [comment]
We will consider in a following update. Currently a qubit is the only important entity. A qureg is just a list of qubits...

**Pull request closed without merging**
