### PR TITLE
Upgrade GitHub Actions

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/actions/cache/releases
https://github.com/actions/checkout/releases
https://github.com/actions/setup-python/releases

### CODE REVIEW

**Comment by Takishima** [comment]
This looks good to me. Please update the CHANGELOG file and if you don't have done so already, please send an email to info@projectq.ch to request the CLA so we can get you to sign it electronically.

**Review by Takishima — APPROVED** [review]

**Comment by cclauss** [comment]
I don't sense that this change is significant enough to be added to the CHANGELOG.
I have already requested the CLA.

**Comment by Takishima** [comment]
> I don't sense that this change is significant enough to be added to the CHANGELOG. I have already requested the CLA.

I just saw your email and somebody will get back to you as soon as possible.

**Comment by cclauss** [comment]
I have signed.

**Review by Takishima — COMMENTED** [review]
EDIT: ignore comment

**Comment by Takishima** [comment]
Thanks for the contribution!

**Pull request merged**
